# -*- coding: utf-8 -*-
"""Exercise1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eshg4KiKzYJyzVfMs96B2AKtLy_DLOpL

# Ex1
"""

n1 = int(input('Digite um numero: '))
n2 = int(input('Digite outro numero: '))

print(f'A soma entre {n1} e {n2} é: {n1+n2}\nA subtração entre {n1} e {n2} é: {n1-n2}\nA multiplicação entre {n1} e {n2} é: {n1*n2}\nA divisão entre {n1} e {n2} é: {n1/n2}')

"""# Ex2"""

tempo = int(input('Digite o tempo da viagem em minutos: '))
velocidade = int(input('Digite a velocidade média em km/h: '))

distancia = (tempo/60)*velocidade

litros_usados = round(distancia/12.0, 2)

print(f'O tempo gasto na viagem em horas foi: {round(tempo/60, 2)} horas\nVelocidade Média: {velocidade} Km/h\nDistância: {distancia} Km\nLitros gastos na viagem: {litros_usados} L')