# -*- coding: utf-8 -*-
"""Exercise5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eshg4KiKzYJyzVfMs96B2AKtLy_DLOpL

1. Read a temperature in Celsius and convert it to Fahrenheit.
"""

def temeperature_c():
    degree =  int(input("Enter the temperature in degrees Celsius: "))
    return degree
def calculate(celsius):
  F = (9*celsius+160)/5
  return F
def temperature_F(fahr):
  print(f"The temperature in Fahrenheit is: {fahr}º ")

degree_c = temeperature_c()
degree_f = calculate(degree_c)
temperature_F(degree_f)

"""2. Calculate how many liters of fuel are spent on a trip using a car that does 12 km per liter. To calculate this, the user needs to enter the time spent on the trip and the average speed. After that, the program can calculate the total distance traveled. With all this information, it's possible to calculate the fuel consumption."""

def time_speed():
  time = float(input("Enter the time spent on the trip(minutes): "))
  speed = float(input("Enter the average speed(km/h): "))
  return time, speed
def  distance_calc(time,speed):
  distance = (time/60)*speed
  return distance
def fuel_consumption(distance):
  fuel = distance/12
  return fuel
def show_data(time,speed,distance, fuel):
  print(f"\nThe time spent is: {int(time//60)} hours and {int(time%60)} minutes\nThe average speed is: {speed}km/h\nThe total distance traveled is: {round(distance, 2)} km\nThe fuel consumption is: {round(fuel, 2)} liters")

time, speed = time_speed()
distance = distance_calc(time, speed)
fuel_consumption = fuel_consumption(distance)
show_data(time,speed, distance, fuel_consumption)