# -*- coding: utf-8 -*-
"""Exercise8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eshg4KiKzYJyzVfMs96B2AKtLy_DLOpL

1. Create a class called "Student" with the following attributes:


Name

Grade 1

Grade 2

Create a constructor for the class (__init__)
2. Create the following functions (methods):

Calculate average: returns the arithmetic average of the grades

Show data: only prints the value of all attributes

Result: checks whether the student has passed or failed (if the average is
greater than or equal to 6.0, the student has passed)

3. Create two objects (student1 and student2) and test the functions.
"""

class student:

  def __init__(self, name, grade1,grade2):
    self.name = name
    self.grade1 = grade1
    self.grade2 = grade2

  def average_calc(self):
    self.average = (self.grade1 + self.grade2)/2
    return self.average

  def average_result(self):
    if self.average_calc() >= 6.0 and self.average_calc() <= 10:
      self.result = "passed"
      return self.result
    elif self.average_calc() >= 0.0 and self.average_calc() < 6.0:
      self.result = "failed"
      return self.result
    else:
      self.result = "Invalid grade"
      return self.result
      return self.result

  def show_data(self):
    return print(f"Name: {self.name}\nGrade 1: {self.grade1}\nGrade 2: {self.grade2}\nAverage: {round(self.average_calc(), 2)}\nResult: {self.average_result()}\n")

student1 = student("Gustavo", 5.0, 5.5)
student2 = student("Ariane", 9.0, 7.0)

student1.show_data()
student2.show_data()