# -*- coding: utf-8 -*-
"""Exercise4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eshg4KiKzYJyzVfMs96B2AKtLy_DLOpL

1. Make a loop structure to read 5 integer numbers and store them in a list, then make another loop structure to sum all the values entered
"""

list = []
for i in range (0, 5):
  num = int(input(f"Enter the {i+1}º number: "))
  list.append(num)

sum = 0

for num in list:
  sum+=num
print(f'\n{sum}')

"""2. Make a dictionary to store the name and grade of 3 students. Using a loop structure, read the values, then make another loop structure to sum all the grades and return the average"""

dict = {}
for i in range (0,3):
  name = input(f"Enter the name of the {i+1}º student: ")
  grade = float(input("Enter the grade of this student: "))
  dict[name]= grade
sum = 0
for grade in dict.values():
  sum+=grade
print(f"the average of the grades of the 3 students is: {sum/3}")

"""3. Using the matrix [[3, 4, 1], [3, 1, 5]], make a loop structure to sum all the elements of the matrix"""

import numpy as np
matrix  = np.array([[3,4,1],
                  [4,1,5]])
sum = 0
for i in range (matrix.shape[0]):
  for j in range (matrix.shape[1]):
    sum+=matrix[i][j]
print(f"The sum of all the elements of the matrix is: {sum}")