# -*- coding: utf-8 -*-
"""Exercise2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eshg4KiKzYJyzVfMs96B2AKtLy_DLOpL

1. Leia a idade do usuário e classifique-o em:
- Criança – 0 a 12 anos
- Adolescente – 13 a 17 anos
- Adulto – acima de 18 anos
-Se o usuário digitar um número negativo, mostrar a mensagem que a idade é inválida
"""

idade = int(input("Digite a idade: "))

if idade >= 0 and idade <= 12:
  print("Criança")
elif idade < 18:
  print("Adolecente")
elif idade >= 18:
  print("Adulto")
else:
  print("Idade inválida")

"""2. Calcular a média de um aluno que cursou a disciplina de Programação I, a partir da leitura das notas M1, M2 e M3; passando por um cálculo da média aritmética. Após a média calculada, devemos anunciar se o aluno foi aprovado, reprovado ou pegou exame
- Se a média estiver entre 0.0 e 4.0, o aluno está reprovado
- Se a média estiver entre 4.1 e 6.0, o aluno pegou exame
- Se a média for maior do que 6.0, o aluno está aprovado
- Se o aluno pegou exame, deve ser lida a nota do exame. Se a nota do exame for maior do que 6.0, está aprovado, senão; está reprovado
"""

m1 = float(input("Digite a nota 1 :"))
m2 = float(input("Digite a nota 2: "))
m3 = float(input("Digite a nota 3: "))

media = (m1+ m2+ m3)/3

print(round(media, 2))
if media >= 0 and media <= 4:
  print("Reprovado")
elif media <= 6.0:
  print("Recuperação")
  nota_rec = float(input("Digite a nota tirada na recuperação: "))
  if nota_rec >= 6 and nota_rec <= 10:
    print("Aprovado")
  elif nota_rec < 6 and nota_rec >= 0:
    print("Reprovado")
elif media >= 6 and media <= 10:
  print("Aprovado")
else:
  print("Valores invalidos")