# -*- coding: utf-8 -*-
"""Exercise7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eshg4KiKzYJyzVfMs96B2AKtLy_DLOpL
"""

import re

phones = "For assistance, please contact us at (19)97552-2498, (14)98147-3059, or (71)99632-7581."

re.findall('\(\d{2}\)\d{5}-\d{4}', phones)

ceps = "Our offices are located at 13080-120, 13092-345, and 13076-890."

re.findall('\d{5}-\d{3}', ceps)

urls = "For more information, visit www.company.com, www.services.net, or www.contact.org."

re.findall('wwww?.[A-Za-z0-9./]+', urls)