# -*- coding: utf-8 -*-
"""Exercise3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eshg4KiKzYJyzVfMs96B2AKtLy_DLOpL

1. Read 5 grades and give the average
"""

sum = 0
for grade in range(1, 6):
  grade = float(input(f"Enter your {grade}º grade: "))
  sum += grade
average = sum/5
print("Your average is: ", average)

"""2. Print the time table of number 3."""

for number in range(1, 11):
  print(f"3x{number} = {3*number}" )