# -*- coding: utf-8 -*-
"""Exercise6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eshg4KiKzYJyzVfMs96B2AKtLy_DLOpL

1. Consider a dictionary with the names and grades of some students. Make a loop structure to iterate through the dictionary and write each student's name and grade to a text file.
"""

students = {'Pedro': 8.0, 'Maria': 10.0, 'Amilton': 7.5}

with open ("students_grades.txt", 'w') as file:
  for name, grade in students.items():
    file.write(f"nome: {name}, nota: {grade}\n")

with open ("students_grades.txt") as file:
  for line in file:
    print(line)